import { MockServerConfig, RouteConfig } from '../types/core.js';

/**
 * Deterministic Markdown API documentation generator. Produces complete,
 * accurate reference docs from a server configuration without any AI —
 * used standalone and as grounding context for Copilot-enhanced docs.
 */
export class DocsService {
  /**
   * Generate Markdown reference documentation for a server.
   */
  generateMarkdown(server: MockServerConfig): string {
    const lines: string[] = [];
    const routes = server.routes.filter((r) => r.enabled);

    lines.push(`# ${server.name} — API Documentation`);
    lines.push('');
    lines.push(`> Generated by [Mocklify](https://github.com/sitharaj88/mocklify) on ${new Date().toISOString().slice(0, 10)}`);
    lines.push('');
    lines.push(`**Base URL:** \`http://localhost:${server.port}\``);
    lines.push(`**Protocol:** ${server.protocol.toUpperCase()}`);
    lines.push(`**Endpoints:** ${routes.length}`);
    lines.push('');

    if (routes.length === 0) {
      lines.push('_This server has no enabled routes yet._');
      return lines.join('\n');
    }

    lines.push('## Endpoints');
    lines.push('');
    lines.push('| Method | Path | Name | Status |');
    lines.push('|--------|------|------|--------|');
    for (const route of routes) {
      const methods = Array.isArray(route.method) ? route.method.join(', ') : route.method;
      lines.push(
        `| \`${methods}\` | \`${route.path}\` | ${route.name} | ${route.response.statusCode} |`
      );
    }
    lines.push('');

    const grouped = this.groupByTag(routes);
    for (const [tag, tagRoutes] of grouped) {
      if (grouped.size > 1) {
        lines.push(`## ${tag}`);
        lines.push('');
      }
      for (const route of tagRoutes) {
        lines.push(...this.renderRoute(route, server.port));
      }
    }

    return lines.join('\n');
  }

  private renderRoute(route: RouteConfig, port: number): string[] {
    const lines: string[] = [];
    const methods = Array.isArray(route.method) ? route.method : [route.method];
    const primaryMethod = methods[0];

    lines.push(`### ${route.name}`);
    lines.push('');
    lines.push(`\`\`\`http`);
    for (const method of methods) {
      lines.push(`${method} ${route.path}`);
    }
    lines.push('```');
    lines.push('');

    const pathParams = Array.from(route.path.matchAll(/:([A-Za-z0-9_]+)/g)).map((m) => m[1]);
    if (pathParams.length > 0) {
      lines.push('**Path parameters:**');
      lines.push('');
      for (const param of pathParams) {
        lines.push(`- \`${param}\` (string, required)`);
      }
      lines.push('');
    }

    if (route.matcher?.queryParams && Object.keys(route.matcher.queryParams).length > 0) {
      lines.push('**Query parameters:**');
      lines.push('');
      for (const [name, value] of Object.entries(route.matcher.queryParams)) {
        lines.push(`- \`${name}\` — matched value: \`${value}\``);
      }
      lines.push('');
    }

    if (route.matcher?.headers && Object.keys(route.matcher.headers).length > 0) {
      lines.push('**Required headers:**');
      lines.push('');
      for (const [name, value] of Object.entries(route.matcher.headers)) {
        lines.push(`- \`${name}: ${value}\``);
      }
      lines.push('');
    }

    lines.push(`**Response:** \`${route.response.statusCode}\``);
    if (route.response.type !== 'static') {
      lines.push('');
      lines.push(`_Response type: ${route.response.type}_`);
    }
    lines.push('');

    const body = route.response.body?.content;
    if (body !== undefined && body !== null) {
      lines.push('```json');
      lines.push(typeof body === 'string' ? body : JSON.stringify(body, null, 2));
      lines.push('```');
      lines.push('');
    } else if (route.response.template) {
      lines.push('_Dynamic response generated from template:_');
      lines.push('');
      lines.push('```handlebars');
      lines.push(route.response.template.template);
      lines.push('```');
      lines.push('');
    }

    lines.push('**Example request:**');
    lines.push('');
    lines.push('```bash');
    lines.push(this.buildCurl(primaryMethod, route.path, port));
    lines.push('```');
    lines.push('');

    return lines;
  }

  private buildCurl(method: string, path: string, port: number): string {
    const url = `http://localhost:${port}${path.replace(/:([A-Za-z0-9_]+)/g, '{$1}')}`;
    const parts = [`curl`];
    if (method !== 'GET') {
      parts.push(`-X ${method}`);
    }
    if (['POST', 'PUT', 'PATCH'].includes(method)) {
      parts.push(`-H 'Content-Type: application/json'`, `-d '{}'`);
    }
    parts.push(`'${url}'`);
    return parts.join(' \\\n  ');
  }

  private groupByTag(routes: RouteConfig[]): Map<string, RouteConfig[]> {
    const grouped = new Map<string, RouteConfig[]>();
    for (const route of routes) {
      const tag = route.tags?.[0] ?? 'General';
      const list = grouped.get(tag) ?? [];
      list.push(route);
      grouped.set(tag, list);
    }
    return grouped;
  }
}
