import {
  MockServerConfig,
  RouteConfig,
  ResponseConfig,
  HttpMethod,
} from '../types/core.js';

interface OpenApiSpec {
  openapi: string;
  info: {
    title: string;
    version: string;
    description?: string;
  };
  servers: { url: string; description?: string }[];
  tags?: { name: string }[];
  paths: Record<string, Record<string, OpenApiOperation>>;
}

interface OpenApiOperation {
  summary?: string;
  operationId?: string;
  tags?: string[];
  parameters?: OpenApiParameter[];
  responses: Record<string, OpenApiResponse>;
}

interface OpenApiParameter {
  name: string;
  in: 'path' | 'query' | 'header';
  required: boolean;
  schema: { type: string };
}

interface OpenApiResponse {
  description: string;
  content?: Record<string, { schema?: unknown; example?: unknown }>;
}

const STATUS_DESCRIPTIONS: Record<number, string> = {
  200: 'Successful response',
  201: 'Resource created',
  202: 'Accepted',
  204: 'No content',
  400: 'Bad request',
  401: 'Unauthorized',
  403: 'Forbidden',
  404: 'Not found',
  409: 'Conflict',
  422: 'Unprocessable entity',
  429: 'Too many requests',
  500: 'Internal server error',
  502: 'Bad gateway',
  503: 'Service unavailable',
};

/**
 * Generates an OpenAPI 3.0 specification from a Mocklify server configuration.
 * Response schemas are inferred from the configured example bodies.
 */
export class OpenApiExportService {
  /**
   * Convert a server configuration to an OpenAPI 3.0 document.
   */
  exportToOpenApi(server: MockServerConfig, options?: { includeDisabled?: boolean }): OpenApiSpec {
    const routes = server.routes.filter((r) => options?.includeDisabled || r.enabled);

    const paths: OpenApiSpec['paths'] = {};
    const tagSet = new Set<string>();

    for (const route of routes) {
      const oasPath = this.toOpenApiPath(route.path);
      const methods = Array.isArray(route.method) ? route.method : [route.method];

      paths[oasPath] = paths[oasPath] ?? {};
      for (const method of methods) {
        paths[oasPath][method.toLowerCase()] = this.buildOperation(route, method, oasPath);
        for (const tag of route.tags ?? []) {
          tagSet.add(tag);
        }
      }
    }

    const spec: OpenApiSpec = {
      openapi: '3.0.3',
      info: {
        title: server.name,
        version: '1.0.0',
        description: `Mock API generated by Mocklify from server "${server.name}".`,
      },
      servers: [
        {
          url: `http://localhost:${server.port}`,
          description: 'Mocklify mock server',
        },
      ],
      paths,
    };

    if (tagSet.size > 0) {
      spec.tags = Array.from(tagSet)
        .sort()
        .map((name) => ({ name }));
    }

    return spec;
  }

  /**
   * Convert a server configuration to a pretty-printed OpenAPI JSON string.
   */
  exportToJson(server: MockServerConfig, options?: { includeDisabled?: boolean }): string {
    return JSON.stringify(this.exportToOpenApi(server, options), null, 2);
  }

  /** Convert Express-style :param segments to OpenAPI {param} segments. */
  toOpenApiPath(path: string): string {
    return path.replace(/:([A-Za-z0-9_]+)/g, '{$1}');
  }

  private buildOperation(route: RouteConfig, method: HttpMethod, oasPath: string): OpenApiOperation {
    const operation: OpenApiOperation = {
      summary: route.name,
      operationId: this.toOperationId(method, route.path),
      responses: {
        [String(route.response.statusCode)]: this.buildResponse(route.response),
      },
    };

    if (route.tags && route.tags.length > 0) {
      operation.tags = route.tags;
    }

    const parameters: OpenApiParameter[] = [];
    for (const match of oasPath.matchAll(/\{([A-Za-z0-9_]+)\}/g)) {
      parameters.push({
        name: match[1],
        in: 'path',
        required: true,
        schema: { type: 'string' },
      });
    }
    for (const name of Object.keys(route.matcher?.queryParams ?? {})) {
      parameters.push({ name, in: 'query', required: false, schema: { type: 'string' } });
    }
    for (const name of Object.keys(route.matcher?.headers ?? {})) {
      parameters.push({ name, in: 'header', required: false, schema: { type: 'string' } });
    }
    if (parameters.length > 0) {
      operation.parameters = parameters;
    }

    return operation;
  }

  private buildResponse(response: ResponseConfig): OpenApiResponse {
    const description =
      STATUS_DESCRIPTIONS[response.statusCode] ?? `Response with status ${response.statusCode}`;

    const example = response.body?.content;
    if (example === undefined || example === null) {
      return { description };
    }

    const contentType = response.body?.contentType ?? 'application/json';
    return {
      description,
      content: {
        [contentType]: {
          schema: this.inferSchema(example),
          example,
        },
      },
    };
  }

  /** Infer a JSON schema from an example value. */
  inferSchema(value: unknown): unknown {
    if (value === null) {
      return { nullable: true };
    }
    if (Array.isArray(value)) {
      return {
        type: 'array',
        items: value.length > 0 ? this.inferSchema(value[0]) : {},
      };
    }
    switch (typeof value) {
      case 'string':
        return { type: 'string' };
      case 'number':
        return Number.isInteger(value) ? { type: 'integer' } : { type: 'number' };
      case 'boolean':
        return { type: 'boolean' };
      case 'object': {
        const properties: Record<string, unknown> = {};
        for (const [key, val] of Object.entries(value as Record<string, unknown>)) {
          properties[key] = this.inferSchema(val);
        }
        return { type: 'object', properties };
      }
      default:
        return {};
    }
  }

  private toOperationId(method: HttpMethod, path: string): string {
    const parts = path
      .split('/')
      .filter(Boolean)
      .map((segment) =>
        segment.startsWith(':')
          ? `By${this.capitalize(segment.slice(1))}`
          : this.capitalize(segment.replace(/[^A-Za-z0-9]/g, ''))
      );
    return method.toLowerCase() + parts.join('');
  }

  private capitalize(value: string): string {
    return value.charAt(0).toUpperCase() + value.slice(1);
  }
}
