export { CopilotService, CopilotUnavailableError } from './CopilotService.js';
export { AiService } from './AiService.js';
export { ApiKeyManager } from './providers/ApiKeyManager.js';
export { AiUnavailableError } from './providers/types.js';
export type { AiProvider, AiProviderId, AiRequestOptions } from './providers/types.js';
export { MockGenerator } from './MockGenerator.js';
export { CodebaseMockGenerator } from './CodebaseMockGenerator.js';
export type { ScanStrategy, ScanStrategyReport } from './CodebaseMockGenerator.js';
export { ScanOrchestrator } from './ScanOrchestrator.js';
export type { ScanMode } from './ScanOrchestrator.js';
export type { GeneratedServer } from './MockGenerator.js';
export { DocumentationGenerator } from './DocumentationGenerator.js';
export { MocklifyChatParticipant, PARTICIPANT_ID } from './ChatParticipant.js';
export { registerLanguageModelTools } from './LmTools.js';
export { registerAiCommands } from './AiCommands.js';
export { createServerToolBelt, restoreUndoSnapshot, resolveServerRef, MUTATION_DENIED_MESSAGE } from './agent/serverTools.js';
export type { ServerToolsHost, ServerToolBelt, ConfirmHandler, ConfirmAction, ConfirmChange, RouteChangeSnapshot, RouteFieldDiff, ExecutedAction, UndoSnapshot, UndoRestoreResult, ServerAgentActionKind } from './agent/serverTools.js';
export { createKnowledgeTool, createDefaultKnowledgeHost, KNOWLEDGE_TOPICS } from './agent/knowledgeTool.js';
export type { KnowledgeTool, KnowledgeHost, KnowledgeTopic, KnowledgeDiagnostics, KnowledgeManagerSlice } from './agent/knowledgeTool.js';
export { runServerAgentTurn, buildServerAgentPrompt, SERVER_AGENT_MAX_TOOL_CALLS } from './agent/serverAgent.js';
export type { ServerAgentAi, ServerAgentDeps, ServerAgentRequest, ServerAgentTurnResult, ServerAgentTurnMessage } from './agent/serverAgent.js';
export { ProactiveController } from './proactive/proactiveController.js';
export type { ProactiveControllerDeps } from './proactive/proactiveController.js';
export { buildDriftProposal, driftFingerprint } from './proactive/driftProposal.js';
export type { DriftReport, DriftProposal, DriftServerInfo } from './proactive/driftProposal.js';
export { isPathCovered } from './proactive/pathCoverage.js';
export { NotificationLedger, DRIFT_COOLDOWN_MS, RESCAN_COOLDOWN_MS } from './proactive/notificationLedger.js';
export { diffRescan, rescanFingerprint, buildRescanNotificationText, buildRescanChatPrompt } from './proactive/rescanDiffer.js';
export type { RescanDiff, RescanRoute, RescanServerInfo, RescanSurfaceRef, RescanEndpoint } from './proactive/rescanDiffer.js';
export { RescanScheduler, clampIntervalMs, backoffDelayMs } from './proactive/rescanScheduler.js';
export type { RescanSkipReason, RescanSchedulerDeps, RescanTimer } from './proactive/rescanScheduler.js';
export { createScanActivity, sharedScanActivity } from './proactive/scanActivity.js';
export type { ScanActivity } from './proactive/scanActivity.js';
